创建数据

In [1]:
import pandas as pd

pd.DataFrame({'apple':[22], 'banana':[5]})

   apple  banana
0     22       5

读取csv文件

In [11]:
import pandas as pd
df = pd.read_csv('D:\\VSProject\\career-ai\\high_rated_movies.csv')
df.head()

,名称,评分,类型,简介,上映日期,时长,导演,主演
0,蝙蝠侠：骑士陨落 第一部：骑士陨落,92,"动画, 动作, 冒险, 科幻",被称为“贝恩”的神秘巨兽只身突破阿卡姆疯人院，将蝙蝠侠的全部宿敌尽数释放到哥谭街头，整座城市...,2026-08-25 (US),1h 19m,"比尔·芬格, 鲍勃·凯恩, Jeff Wamester, Jeremy Adams","安森·蒙特, 迈克尔·曼多, 巴勃罗·施赖伯, 杰夫·本内特, 路易斯·贝穆德斯, 布鲁斯·..."
1,安昂传奇：最后的气宗,91,"动画, 冒险, 奇幻, 动作",派拉蒙和尼克宣布“降世神通”系列开发三部新的电影，仍是动画形式。第一部由《降世神通：最后的气...,2026-07-24 (US),1h 39m,"Tim Hedrick, 劳伦·蒙哥马利, 克里斯托弗·L·约斯特, Kenneth Lin...","Eric Nam, 戴夫·巴蒂斯塔, 杰西卡·马滕, Román Zaragoza, 史蒂文..."
2,奇幻变身大冒险,89,"冒险, 动画, 家庭, 奇幻",森林中的一个小生物和一只高贵的鸟突然互换了身体，他们不得不结伴而行，共同应对此生最疯狂的冒险。,2026-05-01 (US),1h 42m,"内森·格雷诺, Robert Snow, Christian Magalhaes, 约翰·惠...","迈克尔·B·乔丹, 朱诺·坦普尔, 特雷西·摩根, 塞德里克·凯尔斯, 贾斯蒂娜·马查多, ..."
3,不期而遇的姐妹,88,"喜剧, 爱情",两位女子发现自己被同一个男人欺骗，且两人都被他弄怀孕了。于是她们联手展开报复。,2026-03-12 (MX),1h 25m,"Ihtzi Hurtado, Carmen Castro, Mariana Palos, M...","安吉丽娅·博耶, Bárbara de Regil, Diego Klein, Lucía ..."
4,鬼灭之刃：无限城篇 第一章 猗窝座再袭,88,"动画, 动作, 奇幻",当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...,2025-11-14 (CN),2h 35m,"外崎春雄, 近藤光, 吾峠呼世晴","花江夏树, 樱井孝宏, 石田彰, 下野纮, 细谷佳正, 早见沙织, 宫野真守, 上田丽奈, ..."

In [ ]:
import pandas as pd

# 清洗数据

df = pd.read_csv('D:\\VSProject\\career-ai\\high_rated_movies.csv')

# 去掉上映日期中的换行符和多余空白
# 例如："\n        2026-08-25 (US)\n      " -> "2026-08-25 (US)"
df['上映日期'] = df['上映日期'].fillna('').astype(str).str.replace(r'\s+', ' ', regex=True).str.strip()
df['时长'] = df['时长'].fillna('').astype(str).str.replace(r'\s+', ' ', regex=True).str.strip()
# 直接写回原文件，覆盖原 CSV
df.to_csv('D:\\VSProject\\career-ai\\high_rated_movies.csv', index=False, encoding='utf-8')

df['上映日期'].describe()

df['时长'].describe()

count        100
unique        70
top       1h 42m
freq           4
Name: 时长, dtype: object

In [12]:
import pandas as pd
df = pd.read_csv('D:\\VSProject\\career-ai\\high_rated_movies.csv')
# print(df['名称'])
# print(df.名称)

# 获取第一行数据
df.iloc[0]

# 获取第一列数据
df.iloc[:, 0]
#获取第2行到第3行，第1列数据
df.iloc[1:3,0]

df.iloc[[0, 1, 2], 0]

# 标签选择
df.loc[0:2, '名称']

df.loc[(df['评分'].isin([88, 89]))]

df.loc[(df['评分'].between(88, 95))]

,名称,评分,类型,简介,上映日期,时长,导演,主演
0,蝙蝠侠：骑士陨落 第一部：骑士陨落,92,"动画, 动作, 冒险, 科幻",被称为“贝恩”的神秘巨兽只身突破阿卡姆疯人院，将蝙蝠侠的全部宿敌尽数释放到哥谭街头，整座城市...,2026-08-25 (US),1h 19m,"比尔·芬格, 鲍勃·凯恩, Jeff Wamester, Jeremy Adams","安森·蒙特, 迈克尔·曼多, 巴勃罗·施赖伯, 杰夫·本内特, 路易斯·贝穆德斯, 布鲁斯·..."
1,安昂传奇：最后的气宗,91,"动画, 冒险, 奇幻, 动作",派拉蒙和尼克宣布“降世神通”系列开发三部新的电影，仍是动画形式。第一部由《降世神通：最后的气...,2026-07-24 (US),1h 39m,"Tim Hedrick, 劳伦·蒙哥马利, 克里斯托弗·L·约斯特, Kenneth Lin...","Eric Nam, 戴夫·巴蒂斯塔, 杰西卡·马滕, Román Zaragoza, 史蒂文..."
2,奇幻变身大冒险,89,"冒险, 动画, 家庭, 奇幻",森林中的一个小生物和一只高贵的鸟突然互换了身体，他们不得不结伴而行，共同应对此生最疯狂的冒险。,2026-05-01 (US),1h 42m,"内森·格雷诺, Robert Snow, Christian Magalhaes, 约翰·惠...","迈克尔·B·乔丹, 朱诺·坦普尔, 特雷西·摩根, 塞德里克·凯尔斯, 贾斯蒂娜·马查多, ..."
3,不期而遇的姐妹,88,"喜剧, 爱情",两位女子发现自己被同一个男人欺骗，且两人都被他弄怀孕了。于是她们联手展开报复。,2026-03-12 (MX),1h 25m,"Ihtzi Hurtado, Carmen Castro, Mariana Palos, M...","安吉丽娅·博耶, Bárbara de Regil, Diego Klein, Lucía ..."
4,鬼灭之刃：无限城篇 第一章 猗窝座再袭,88,"动画, 动作, 奇幻",当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...,2025-11-14 (CN),2h 35m,"外崎春雄, 近藤光, 吾峠呼世晴","花江夏树, 樱井孝宏, 石田彰, 下野纮, 细谷佳正, 早见沙织, 宫野真守, 上田丽奈, ..."
5,夜巡毒枭,88,"犯罪, 动作, 惊悚",两位墨西哥员警不幸得罪一名残忍的毒枭后，必须拼命撑过值勤的最后几小时。改编自真实事件。,2026-08-21 (MX),1h 31m,"Chava Cartas, Bernardo Esquinca","Alfonso Herrera, 诺伊·埃尔南德斯, Hector Kotsifakis, ..."

In [ ]:
import pandas as pd
df = pd.read_csv('D:\\VSProject\\career-ai\\high_rated_movies.csv')
# 排序
df.sort_values(by='评分', ascending=False)

,名称,评分,类型,简介,上映日期,时长,导演,主演
0,蝙蝠侠：骑士陨落 第一部：骑士陨落,92,"动画, 动作, 冒险, 科幻",被称为“贝恩”的神秘巨兽只身突破阿卡姆疯人院，将蝙蝠侠的全部宿敌尽数释放到哥谭街头，整座城市...,2026-08-25 (US),1h 19m,"比尔·芬格, 鲍勃·凯恩, Jeff Wamester, Jeremy Adams","安森·蒙特, 迈克尔·曼多, 巴勃罗·施赖伯, 杰夫·本内特, 路易斯·贝穆德斯, 布鲁斯·..."
1,安昂传奇：最后的气宗,91,"动画, 冒险, 奇幻, 动作",派拉蒙和尼克宣布“降世神通”系列开发三部新的电影，仍是动画形式。第一部由《降世神通：最后的气...,2026-07-24 (US),1h 39m,"Tim Hedrick, 劳伦·蒙哥马利, 克里斯托弗·L·约斯特, Kenneth Lin...","Eric Nam, 戴夫·巴蒂斯塔, 杰西卡·马滕, Román Zaragoza, 史蒂文..."
2,奇幻变身大冒险,89,"冒险, 动画, 家庭, 奇幻",森林中的一个小生物和一只高贵的鸟突然互换了身体，他们不得不结伴而行，共同应对此生最疯狂的冒险。,2026-05-01 (US),1h 42m,"内森·格雷诺, Robert Snow, Christian Magalhaes, 约翰·惠...","迈克尔·B·乔丹, 朱诺·坦普尔, 特雷西·摩根, 塞德里克·凯尔斯, 贾斯蒂娜·马查多, ..."
3,不期而遇的姐妹,88,"喜剧, 爱情",两位女子发现自己被同一个男人欺骗，且两人都被他弄怀孕了。于是她们联手展开报复。,2026-03-12 (MX),1h 25m,"Ihtzi Hurtado, Carmen Castro, Mariana Palos, M...","安吉丽娅·博耶, Bárbara de Regil, Diego Klein, Lucía ..."
4,鬼灭之刃：无限城篇 第一章 猗窝座再袭,88,"动画, 动作, 奇幻",当鬼杀队的成员和柱之人在为即将到来的与鬼的战斗做准备，完成共同的体能训练——柱之训练时，鬼舞...,2025-11-14 (CN),2h 35m,"外崎春雄, 近藤光, 吾峠呼世晴","花江夏树, 樱井孝宏, 石田彰, 下野纮, 细谷佳正, 早见沙织, 宫野真守, 上田丽奈, ..."
...,...,...,...,...,...,...,...,...
95,触不可及,83,"剧情, 喜剧",富有的菲利普因一场滑翔伞事故导致高位瘫痪，需要招聘一名全职陪护。前来应聘的人络绎不绝，却始终...,2011-11-02 (FR),1h 52m,"奥利维埃·纳卡什, 埃里克·托莱达诺, 菲利普·波佐·迪·博尔戈","弗朗索瓦·克鲁塞, 奥玛·希, 安娜·勒尼, 奥黛丽·弗洛罗, Joséphine de M..."
96,日落大道,83,剧情,好莱坞的声名终会消散——只需问问诺玛·戴斯蒙德。她曾是影坛传奇，如今已成被人遗忘的旧时代残影...,2026-04-16 (CN),1h 50m,"比利·怀尔德, 查尔斯·威廉·布莱克特, 小D.M.马什曼","威廉·霍尔顿, 格洛丽亚·斯旺森, 埃里克·冯·施特罗海姆, 南希·奥尔森, 弗雷德·克拉克..."
97,西部往事,83,"剧情, 西部",塞尔吉奥·莱昂内的这部不朽史诗，其恢弘堪比取景地纪念碑谷，其气度媲美星光熠熠的杰出演员阵容，...,2018-04-16 (CN),2h 46m,"赛尔乔·莱昂内, 塞尔吉奥·多纳蒂, 贝纳尔多·贝托鲁奇, 达里欧·阿基多","克劳迪娅·卡汀娜, 亨利·方达, 杰森·罗巴兹, 查尔斯·布朗森, 加布里埃尔·费泽蒂, P..."
98,现代启示录,83,"剧情, 战争",越战期间，威拉德上尉受命执行一项危险任务，深入柬埔寨刺杀一位脱离建制的叛变上校——此人已在当...,1979-05-19 (CN),3h 22m,"弗朗西斯·科波拉, 约瑟夫·康拉德, 约翰·米利厄斯","马丁·辛, 马龙·白兰度, 弗雷德里克·福雷斯特, 阿尔伯特·海尔, 劳伦斯·菲什伯恩, 山..."
99,新世纪福音战士剧场版：Air／真心为你,83,"动画, 科幻, 剧情, 奇幻, 动作",《新世纪福音战士》系列第二部剧场版，于 1997 年 7 月 19 日在日本上映。全名：《新...,1997-07-19 (JP),1h 27m,"庵野秀明, 鹤卷和哉","绪方惠美, 林原惠美, 三石琴乃, 宫村优子, 立木文彦, 长泽美树, 子安武人, 优希比吕..."